### ISSUE TITLE
Add default SSL Protocol

### ISSUE THREAD

**Issue by CF-FHB-X** [nbgallery/pypki3#5]
As of Python 3.10, creating an `SSLContext` without protocol argument is deprecated and throws `DeprecationWarning: ssl.PROTOCOL_TLS is deprecated` (see https://docs.python.org/3/library/ssl.html#id9 for more info).

Should be an easy fix of defaulting to `ssl.PROTOCOL_TLS_CLIENT`.

**Comment by billallen256** [comment]
And it looks like `ssl.PROTOCOL_TLS_CLIENT` was added in Python 3.6, so this fix should work on older systems as well.

**Comment by billallen256** [comment]
Resolved in 9fc4276.
